config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'subs#index'
  
  resource :session
  resources :users
  resources :subs do
    resources :posts
  end
  resources :posts do
    resources :comments
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :comments do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
    include Votable

    validates :content, :author_id, :post_id, presence: true

    after_initialize :ensure_post_id!

    belongs_to :author, class_name: 'User', foreign_key: :author_id
    belongs_to :post, class_name: 'Post', foreign_key: :post_id
    belongs_to :parent_comment, class_name: 'Comment', foreign_key: :parent_comment_id, optional: true
    has_many :child_comments, class_name: 'Comment', foreign_key: :parent_comment_id

    private
    def ensure_post_id!
      self.post_id ||= self.parent_comment.post_id if parent_comment
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = current_user.authored_comments.new(comment_params)
        @comment.post_id = params[:post_id]
        @post = Post.find(params[:post_id])
        if @comment.save
            redirect_back(fallback_location: post_url(@post))
        else
            render json:@comment.errors.full_messages
        end
    end

    def upvote
        cast_vote(1)
    end

    def downvote
        cast_vote(-1)
    end

    private
    def comment_params
        params.require(:comment).permit(:content, :parent_comment_id)
    end

    def cast_vote(direction)
        @comment = Comment.find(params[:id])
        @vote = @comment.votes.find_or_initialize_by(user: current_user)
        unless @vote.update(value: direction)
          flash[:errors] = @vote.errors.full_messages
        end
        redirect_to post_url(@comment.post)
    end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%=render 'comments/vote_buttons', comment: comment, votes_count: comment.votes_count%>
<a href="<%=user_path(comment.author)%>"><%=comment.author.username %></a>
<br>

<%= comment.content %>
<form action="<%=post_comments_path(@post)%>" method="post">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <input name="comment[parent_comment_id]" value="<%=comment.id%>" type="hidden">
    <textarea id="comment_content" name="comment[content]"></textarea>
    <input type="submit" value="Comment">
</form>   
<ul>
  <% comments_by_parent[comment.id].each do |child_comment| %>
    <li><%= render("comments/comment",
            comment: child_comment,
            comments_by_parent: comments_by_parent) %></li>
  <% end %>
</ul>

app/views/comments/_vote_buttons.html.erb
<form action="<%=upvote_comment_url(comment)%>" method="post">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <input type="submit" value="u">
</form>
<%=votes_count%>
<form action="<%=downvote_comment_url(comment)%>" method="post">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <input type="submit" value="d">
</form>