config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'subs#index'
  
  resource :session
  resources :users
  resources :subs do
    resources :posts
  end
  resources :posts do
    resources :comments
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :comments do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    attr_reader :password

    validates :username, :password_digest, :session_token, presence: true
    validates :username, :session_token, uniqueness: true
    validates :password, length: {minimum: 6}, allow_nil: true

    after_initialize :ensure_session_token

    has_many :created_subs, class_name: 'Sub', foreign_key: :moderator_id
    has_many :authored_posts, class_name: 'Post', foreign_key: :author_id
    has_many :authored_comments, class_name: 'Comment', foreign_key: :author_id
    

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(password_digest).is_password?(password)
    end

    def reset_session_token
        self.session_token = generate_session_token
        self.save!
        self.session_token
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end

    private

    def generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def ensure_session_token
        self.session_token ||= generate_session_token
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_no_user, only: %i(new create)

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in(@user)
            render :index
        else
            render json:@user.errors.full_messages
        end
    end

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    private
    def user_params
        params.require(:user).permit(:username, :password, :email)
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>All users</h1>
<ul>
    <% User.all.each do |user| %>
        <li><%=user.username%></li>
    <%end%>
    current user is <%=current_user ? current_user.username : 'n/a'%>

    <form action="<%=session_path%>" method="post">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input name="_method" type="hidden" value="delete">
        <input type="submit" value="log out">
    </form>

    <form action="<%=new_session_path%>" method="get">
        <input type="submit" value="log in">
    </form>

    <form action="<%=new_user_path%>" method="get">
        <input type="submit" value="create user">
    </form>
</ul>

app/views/users/new.html.erb
<h1>New user</h1>
<form action="<%= users_path %>" method="post">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    
    <label>Username:
        <input id="username" name="user[username]" type="text">
    </label>
    <br>

    <label>Password:
        <input id="password" name="user[password]" type="text">
    </label>
    <br>

    <input type="submit" value="Create User">
</form>

app/views/users/show.html.erb
<h1><%=@user.username%></h1>