config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'subs#index'
  
  resource :session
  resources :users
  resources :subs do
    resources :posts
  end
  resources :posts do
    resources :comments
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :comments do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
end

app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :moderator_id, presence: true
    validates :title, uniqueness: true

    belongs_to :moderator, class_name: 'User', foreign_key: :moderator_id
    has_many :sub_posts, class_name: 'Post', foreign_key: :primary_sub_id
    has_many :crosspost_sub_associations, class_name: 'PostSub', inverse_of: :sub

    has_many :cross_posts, through: :crosspost_sub_associations, source: :post

    def all_posts
        (cross_posts.all + sub_posts.all).uniq
    end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_user, only: %i(new create edit update)

    def new
        @sub = Sub.new
    end

    def create
        @sub = current_user.created_subs.new(sub_params)
        if @sub.save
            render :show
        else
            redirect_to(subs_url)
        end
    end

    def edit
        @sub = Sub.find(params[:id])
    end

    def update
        @sub = Sub.find(params[:id])
        @sub.update_attributes(sub_params)
        if @sub.save
            render :show    
        else
            redirect_to(subs_url)
        end
    end

    def show
        @sub = Sub.find(params[:id])
    end

    def index
        @subs = Sub.all
    end

    private
    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<% form_action = (form_method == 'post' ? subs_path : sub_path(sub)) %>
<% button_msg = (form_method == 'post' ? 'Create Sub' : 'Edit Sub') %>

<form action="<%= form_action %>" method="post">
    <input type="hidden" name="_method" value="<%=form_method%>">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    
    <label>Title:
        <input id="title" name="sub[title]" type="text" value="<%= sub.title%>">
    </label>
    <br>

    <label>Description:
        <textarea id="description" name="sub[description]"><%= sub.description%></textarea>
    </label>
    <br>

    <input type="submit" value="<%=button_msg%>">
</form>

app/views/subs/edit.html.erb
<h1>Edit sub</h1>
<%= render 'form', sub: @sub, form_method: 'patch'%>

app/views/subs/index.html.erb
<h1>All subs</h1>
<ul>
    <% @subs.each do |sub| %>
        <li><a href="<%=sub_path(sub)%>"><%=sub.title%></a>
            <ul>
                <li><%=sub.moderator.username%></li>
            </ul>
        </li>
    <%end%>
    current user is <%=current_user ? current_user.username : 'n/a'%>

    <form action="<%=new_sub_path%>" method="get">
        <input type="submit" value="create sub">
    </form>
</ul>

app/views/subs/new.html.erb
<h1>New sub</h1>
<%= render 'form', sub: @sub, form_method: 'post'%>

app/views/subs/show.html.erb
<h1><%=@sub.title%></h1>
<ul>
    <li>Created by: <%=@sub.moderator.username%></li>
    <li>Description: <%=@sub.description%></li>
</ul>

<section>
    Mods only:
    <form action="<%=edit_sub_path(@sub)%>" method="get">
        <input type="submit" value="Edit Sub">
    </form>
</section>

<section>
    <% @sub.all_posts.each do |post| %>
        <% xpost = (post.primary_sub_id == @sub.id ? '' : '[x-post: ' + post.primary_sub.title + ']')%>
        <section>
            <h3><a href="<%=sub_post_path(@sub, post)%>"><%=xpost%><%=post.title%></a></h3>
            <p><%=post.author.username%></p>
        </section>
    <% end %>
</section>

<section>
    <form action="<%=new_sub_post_path(@sub)%>" method="get">
        <input type="submit" value="New Post!">
    </form>
</section>

<section>
    <form action="<%=subs_path%>" method="get">
        <input type="submit" value="All Subs">
    </form>
</section>