config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'subs#index'
  
  resource :session
  resources :users
  resources :subs do
    resources :posts
  end
  resources :posts do
    resources :comments
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :comments do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
    include Votable
    
    validates :title, :primary_sub_id, :author_id, presence: true

    belongs_to :primary_sub, class_name: 'Sub', foreign_key: :primary_sub_id
    belongs_to :author, class_name: 'User', foreign_key: :author_id
    has_many :crosspost_sub_associations, class_name: 'PostSub', inverse_of: :post, dependent: :destroy

    has_many :cross_posted_subs, through: :crosspost_sub_associations, source: :sub
    
    has_many :comments, class_name: 'Comment', foreign_key: :post_id

    def comments_by_parent
        comments_by_parent = Hash.new { |hash, key| hash[key] = [] }
    
        self.comments.includes(:author).each do |comment|
          comments_by_parent[comment.parent_comment_id] << comment
        end
    
        comments_by_parent
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_user, only: %i(new create edit update)

    def new
        @sub = Sub.find(params[:sub_id])
        @post = Post.new
    end

    def create
        @post = current_user.authored_posts.new(post_params)
        @post.primary_sub_id = params[:sub_id]
        if @post.save
            @sub ||= @post.primary_sub
            redirect_to(sub_post_url(@sub, @post))  
        else
            render json: @post.errors.full_messages
            # redirect_to(subs_url)
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @post.update_attributes(post_params)
        if @post.save
            @sub ||= @post.primary_sub
            redirect_to(sub_post_url(@sub, @post))    
        else
            redirect_to(subs_url)
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def index
        @posts = Post.all
    end

    def upvote
        cast_vote(1)
    end

    def downvote
        cast_vote(-1)
    end
    
    private
    def post_params
        params.require(:post).permit(:title, :url, :content, cross_posted_sub_ids: [])
    end

    def cast_vote(direction)
        @post = Post.find(params[:id])
        @vote = @post.votes.find_or_initialize_by(user: current_user)
    
        unless @vote.update(value: direction)
          flash[:errors] = @vote.errors.full_messages
        end
    
        redirect_back(fallback_location: post_url(@post))
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% form_action = (form_method == 'post' ? sub_posts_path(@sub) : sub_post_path(sub)) %>
<% button_msg = (form_method == 'post' ? 'Create Post' : 'Edit Post') %>

<form action="<%= form_action %>" method="post">
    <input type="hidden" name="_method" value="<%=form_method%>">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    
    <label>Title:
        <input id="title" name="post[title]" type="text" value="<%= post.title%>">
    </label>
    <br>

    <label>URL:
        <input id="url" name="post[url]" type="text" value="<%= post.url%>">
    </label>
    <br>

    <label>Content:
        <textarea id="content" name="post[content]"><%= post.content%></textarea>
    </label>
    <br>

    <% Sub.all.where.not(id: @sub.id).each do |cross_posted_sub| %>
        <label><%= cross_posted_sub.title %>
        <input
            type="checkbox"
            value="<%= cross_posted_sub.id %>"
            name="post[cross_posted_sub_ids][]"
            <%= "checked" if @post.cross_posted_sub_ids.include?(cross_posted_sub.id) %>
        />
        </label>
    <% end %>
    
    <input type="submit" value="<%=button_msg%>">
</form>

app/views/posts/_vote_buttons.html.erb
<form action="<%=upvote_post_url(post)%>" method="post">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <input type="submit" value="u">
</form>
<%=votes_count%>
<form action="<%=downvote_post_url(post)%>" method="post">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <input type="submit" value="d">
</form>

app/views/posts/new.html.erb
<h1>New post on <%=@sub.title%></h1>
<%= render 'form', sub: @sub, post: @post, form_method: 'post'%>

app/views/posts/show.html.erb
<h1><%=@post.title%></h1>
<%=render 'vote_buttons', post: @post, votes_count: @post.votes_count%>
<ul>
    <li>Created by: <%=@post.author.username%></li>
    <li>Content: <%=@post.content%></li>
</ul>

<section>
    <h3>comments</h3>
        <form action="<%=post_comments_path(@post)%>" method="post">
            <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
            <textarea id="comment_content" name="comment[content]"></textarea>
            <input type="submit" value="Comment">
        </form>
    <ul>
        <% comments_by_parent = @post.comments_by_parent %>
        <% comments_by_parent[nil].each do |top_level_comment| %>
            <li><%=render 'comments/comment',
                comments_by_parent: comments_by_parent,
                comment: top_level_comment%></li>
        <%end%>
    </ul>
</section>

<section>
    <form action="<%=sub_path(@post.primary_sub)%>" method="get">
        <input type="submit" value="Back to <%=@post.primary_sub.title%>">
    </form>
</section>

<section>
    <form action="<%=subs_path%>" method="get">
        <input type="submit" value="All Subs">
    </form>
</section>